library:
  source-dirs: src
tests:
  getting-started-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - getting-started
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
  - HUnit
  - base >= 4.7 && < 5
name: getting-started
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/getting-started
license: BSD3
executables:
  getting-started-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - getting-started
description: Please see the README on GitHub at <https://github.com/githubuser/getting-started#readme>
